/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.aditya.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Employee extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5944081788210123133L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Employee\",\"namespace\":\"com.aditya.avro\",\"fields\":[{\"name\":\"empId\",\"type\":\"int\"},{\"name\":\"empName\",\"type\":\"string\"},{\"name\":\"designation\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Employee> ENCODER =
      new BinaryMessageEncoder<Employee>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Employee> DECODER =
      new BinaryMessageDecoder<Employee>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Employee> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Employee> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Employee>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Employee to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Employee from a ByteBuffer. */
  public static Employee fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int empId;
  @Deprecated public java.lang.CharSequence empName;
  @Deprecated public java.lang.CharSequence designation;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Employee() {}

  /**
   * All-args constructor.
   * @param empId The new value for empId
   * @param empName The new value for empName
   * @param designation The new value for designation
   */
  public Employee(java.lang.Integer empId, java.lang.CharSequence empName, java.lang.CharSequence designation) {
    this.empId = empId;
    this.empName = empName;
    this.designation = designation;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return empId;
    case 1: return empName;
    case 2: return designation;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: empId = (java.lang.Integer)value$; break;
    case 1: empName = (java.lang.CharSequence)value$; break;
    case 2: designation = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'empId' field.
   * @return The value of the 'empId' field.
   */
  public java.lang.Integer getEmpId() {
    return empId;
  }

  /**
   * Sets the value of the 'empId' field.
   * @param value the value to set.
   */
  public void setEmpId(java.lang.Integer value) {
    this.empId = value;
  }

  /**
   * Gets the value of the 'empName' field.
   * @return The value of the 'empName' field.
   */
  public java.lang.CharSequence getEmpName() {
    return empName;
  }

  /**
   * Sets the value of the 'empName' field.
   * @param value the value to set.
   */
  public void setEmpName(java.lang.CharSequence value) {
    this.empName = value;
  }

  /**
   * Gets the value of the 'designation' field.
   * @return The value of the 'designation' field.
   */
  public java.lang.CharSequence getDesignation() {
    return designation;
  }

  /**
   * Sets the value of the 'designation' field.
   * @param value the value to set.
   */
  public void setDesignation(java.lang.CharSequence value) {
    this.designation = value;
  }

  /**
   * Creates a new Employee RecordBuilder.
   * @return A new Employee RecordBuilder
   */
  public static com.aditya.avro.Employee.Builder newBuilder() {
    return new com.aditya.avro.Employee.Builder();
  }

  /**
   * Creates a new Employee RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Employee RecordBuilder
   */
  public static com.aditya.avro.Employee.Builder newBuilder(com.aditya.avro.Employee.Builder other) {
    return new com.aditya.avro.Employee.Builder(other);
  }

  /**
   * Creates a new Employee RecordBuilder by copying an existing Employee instance.
   * @param other The existing instance to copy.
   * @return A new Employee RecordBuilder
   */
  public static com.aditya.avro.Employee.Builder newBuilder(com.aditya.avro.Employee other) {
    return new com.aditya.avro.Employee.Builder(other);
  }

  /**
   * RecordBuilder for Employee instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Employee>
    implements org.apache.avro.data.RecordBuilder<Employee> {

    private int empId;
    private java.lang.CharSequence empName;
    private java.lang.CharSequence designation;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.aditya.avro.Employee.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.empId)) {
        this.empId = data().deepCopy(fields()[0].schema(), other.empId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.empName)) {
        this.empName = data().deepCopy(fields()[1].schema(), other.empName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.designation)) {
        this.designation = data().deepCopy(fields()[2].schema(), other.designation);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Employee instance
     * @param other The existing instance to copy.
     */
    private Builder(com.aditya.avro.Employee other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.empId)) {
        this.empId = data().deepCopy(fields()[0].schema(), other.empId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.empName)) {
        this.empName = data().deepCopy(fields()[1].schema(), other.empName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.designation)) {
        this.designation = data().deepCopy(fields()[2].schema(), other.designation);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'empId' field.
      * @return The value.
      */
    public java.lang.Integer getEmpId() {
      return empId;
    }

    /**
      * Sets the value of the 'empId' field.
      * @param value The value of 'empId'.
      * @return This builder.
      */
    public com.aditya.avro.Employee.Builder setEmpId(int value) {
      validate(fields()[0], value);
      this.empId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'empId' field has been set.
      * @return True if the 'empId' field has been set, false otherwise.
      */
    public boolean hasEmpId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'empId' field.
      * @return This builder.
      */
    public com.aditya.avro.Employee.Builder clearEmpId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'empName' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmpName() {
      return empName;
    }

    /**
      * Sets the value of the 'empName' field.
      * @param value The value of 'empName'.
      * @return This builder.
      */
    public com.aditya.avro.Employee.Builder setEmpName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.empName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'empName' field has been set.
      * @return True if the 'empName' field has been set, false otherwise.
      */
    public boolean hasEmpName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'empName' field.
      * @return This builder.
      */
    public com.aditya.avro.Employee.Builder clearEmpName() {
      empName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'designation' field.
      * @return The value.
      */
    public java.lang.CharSequence getDesignation() {
      return designation;
    }

    /**
      * Sets the value of the 'designation' field.
      * @param value The value of 'designation'.
      * @return This builder.
      */
    public com.aditya.avro.Employee.Builder setDesignation(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.designation = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'designation' field has been set.
      * @return True if the 'designation' field has been set, false otherwise.
      */
    public boolean hasDesignation() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'designation' field.
      * @return This builder.
      */
    public com.aditya.avro.Employee.Builder clearDesignation() {
      designation = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Employee build() {
      try {
        Employee record = new Employee();
        record.empId = fieldSetFlags()[0] ? this.empId : (java.lang.Integer) defaultValue(fields()[0]);
        record.empName = fieldSetFlags()[1] ? this.empName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.designation = fieldSetFlags()[2] ? this.designation : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Employee>
    WRITER$ = (org.apache.avro.io.DatumWriter<Employee>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Employee>
    READER$ = (org.apache.avro.io.DatumReader<Employee>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
